services:
  backend:
    build:
      context: ./backend/vendor_app
      dockerfile: Dockerfile
    container_name: hack-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      - ./backend/vendor_app:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hack-network

  frontend:
    build:
      context: ./frontend/vendor-discovery
      dockerfile: Dockerfile
    container_name: hack-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hack-network

networks:
  hack-network:
    driver: bridge
